// automatically generated by the FlatBuffers compiler, do not modify

package com.eqgis.sceneform.lull;

import com.eqgis.sceneform.flatbuffers.FlatBufferBuilder;
import com.eqgis.sceneform.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
/**
 * Describes a single attribute in vertex format.
 */
public final class VertexAttribute extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public VertexAttribute __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int usage() { return bb.getInt(bb_pos + 0); }
  public int type() { return bb.getInt(bb_pos + 4); }

  public static int createVertexAttribute(FlatBufferBuilder builder, int usage, int type) {
    builder.prep(4, 8);
    builder.putInt(type);
    builder.putInt(usage);
    return builder.offset();
  }
}

